image: registry.gitlab.com/quarto-forge/docker/rstats

pages:
  before_script:
    - curl -fsSL https://d2lang.com/install.sh | sh -s --
    - export PATH=$HOME/.local/bin:$PATH
    - R -e 'install.packages(c("countdown"), repos="http://cran.us.r-project.org")'
  script:
    -  quarto render --output-dir public
  artifacts:
    paths:
      - public
