project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "materials/*.qmd"


website:
  title: "Getting Started with Git/GitHub"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Workshop
        menu: 
          - href: materials/git-github-intro.qmd
            text: "Intro to Git/Github"
          - href: materials/git-training.qmd
            text: "Training with Git/Github"
      #     - href: materials/03-computation-editors.qmd
      #       text: "Code and Editors"
      #     - href: materials/04-static-documents.qmd
      #       text: "Static Documents" 
          - href: materials/git-reminder.qmd
            text: "Git Reminder"
    right: 
      - icon: gitlab
        href: https://forge.ird.fr/marbec/ob7/training/git-training
  sidebar: 
    style: docked
    contents: 
      - section: "Workshop"
        contents: 
          - href: materials/git-github-intro.qmd
            text: "Intro to Git/Github"
          - href: materials/git-training.qmd
            text: "Training with Git/Github"
      #     - href: materials/03-computation-editors.qmd
      #       text: "Code and Editors"
      #     - href: materials/04-static-documents.qmd
      #       text: "Static Documents" 
          - href: materials/git-reminder.qmd
            text: "Git Reminder"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



